name: Shiggy.com
favicon: null
layout_spectrum: 0.00828
typography_spectrum: 0.8463
title: Shiggy.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe0000'
    - '#050505'
    - '#ffcc67'
    - '#2e6d99'
    - '#c96b51'
  brandStrength: 0.25561164575628936
  lightness: 0.8244452620856464
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
