name: Shiggy.com
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Shiggy.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfdfd'
    - '#cc5700'
    - '#d5b000'
    - '#0353e9'
  brandStrength: 1
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 1
purpose: []
