name: Shiggy.com
favicon: null
layout_spectrum: 0.00828
typography_spectrum: 0.8463
title: Shiggy.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b010a'
    - '#735150'
    - '#7f2928'
    - '#2f3c34'
    - '#ce8b5e'
  brandStrength: 0.25561164575628936
  lightness: 0.8244452620856464
  saturation: 0
  rhythmicContrast: 0.6870792421977967
purpose: []
